import Head from "next/head";
import { useContext, useState } from "react";
import HeroSection from "../components/HeroSection/HeroSection";
import PortfolioSection from "../components/PortfolioSection/PortfolioSection";

import { AppThemeContext } from "../context/AppThemeContext/AppThemeContext";

export default function Home() {
  const { toogleThemeMode } = useContext(AppThemeContext);

  const [selectedIndex, setSelectedIndex] = useState(0);

  return (
    <div>
      <Head>
        <title>Dopefolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => toogleThemeMode()}>Theme Switch</button>
      <div>
        <section>
          <HeroSection
            selectedIndex={selectedIndex}
            setSelectedIndex={setSelectedIndex}
          />
        </section>
        <section>
          <PortfolioSection selectedIndex={selectedIndex} />
        </section>
      </div>
    </div>
  );
}
